name: wf-ci-release

on:
  pull_request:
    branches:
      - develop
      - release/v1
    types: [opened, synchronize, reopened]

jobs:
  linting-job:
    name: Lint HTML and CSS source files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          npm install -g stylelint stylelint-config-standard
          npm install -g prettier
          
      - name: Format HTML files
        run: |
          find src -name "*.html" -exec prettier --write --parser html {} \;
          
      - name: Lint HTML files
        run: npx htmlhint "src/**/*.html"
        
      - name: Lint CSS files
        run: npx stylelint "styles/**/*.css"

  build-job:
    name: Build and validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm install
        
      - name: Build with Parcel
        run: npx parcel build "./src/*.html" --dist-dir "./dist" --public-url "./dist"
        
      - name: Format built HTML
        run: |
          find dist -name "*.html" -exec prettier --write --parser html {} \;
          
      - name: Validate HTML
        run: npx htmlhint "dist/**/*.html"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "Build-artifact-release"