name: wf-ci-release

on:
  pull_request:
    branches:
      - develop
      - release/v1
    types: [opened, synchronize, reopened]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g stylelint htmlhint
          npm install

      - name: Lint HTML files
        run: htmlhint "src/**/*.html"

      - name: Lint CSS files
        run: npx stylelint "styles/**/*.css"

      - name: Build project with Parcel
        run: npx parcel build "./src/*.[hH][tT][mM][lL]" --dist-dir "./dist" --public-url ./

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
