name: wf-ci-develop

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  linting-develop-job:
    name: Lint HTML and CSS (src only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Linting Tools
        run: |
          npm install -g stylelint stylelint-config-standard htmlhint

      - name: Lint HTML Files (only src/)
        run: npx htmlhint "src/**/*.html" --config .htmlhintrc || echo "No HTML files found"

      - name: Lint CSS Files (only src/)
        run: npx stylelint "src/**/*.css" --allow-empty-input || echo "No CSS files found"

  build-develop-job:
    name: Build website without minification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build website with Parcel (no optimize)
        run: npx parcel build "./src/*.html" --dist-dir "./dist" --public-url "./" --no-optimize

      - name: Upload build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "Build-artifact-develop"
