name: wf-cd-deploy

on: 
  push:
    branches: 
      - production

jobs:
  Build-job:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to Runner
        uses: actions/checkout@v4
      - name: Build website with Parcel
        run: npx parcel build "./src/*.html" --dist-dir "./dist" --public-url "./"
      - name: Upload build Artifacts to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "Build-artifact-production"

  deploy-job:
    name: Deploy to GitHub Pages
    needs: Build-job
    runs-on: ubuntu-latest
    environment:
      name: "production-env"
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "Build-artifact-production"
          token: "${{ github.token }}"
